09_MtoN/movie_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.profile, name='profile'),
    path('<int:profile_id>/follow/',views.follow, name='follow'),
]

09_MtoN/movie_pjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views as movies_views

urlpatterns = [
    path('', movies_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

09_MtoN/movie_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/scores/new/', views.new_score, name='new_score'),
    path('<int:movie_pk>/scores/<int:score_pk>/delete', views.delete_score, name='delete_score'),
]

09_MtoN/movie_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

09_MtoN/movie_pjt/movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

class Score(models.Model):
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

09_MtoN/movie_pjt/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name',)

09_MtoN/movie_pjt/movies/forms.py
from django import forms
from .models import Score

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['score']

09_MtoN/movie_pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from django.db.models import Q, Max

from .forms import UserCustomCreationForm
from .models import User
from movies.models import Movie, Score

def user_list(request):
    users = User.objects.all()
    return render(request, 'accounts/user_list.html', {'users': users})

def profile(request, user_pk):
    profile = get_object_or_404(User, pk=user_pk)
    if profile.id == user_pk:
        followings = request.user.followings.all()
        scores = Score.objects.order_by('-score')
        recommends = [[followings[_], 0] for _ in range(len(followings))]
        for f in range(len(followings)):
            for score in scores:
                if score.user == recommends[f][0]:
                    recommends[f][1] = Movie.objects.get(id=score.movie.id).title
                    break
        print(profile, recommends)
        return render(request, 'accounts/profile.html', {'profile': profile, 'recommends': recommends})
    return render(request, 'accounts/profile.html', {'profile': profile})

@login_required
def follow(request, profile_id):
    profile = get_object_or_404(get_user_model(), pk=profile_id)
    if request.user in profile.followers.all():
        profile.followers.remove(request.user)
    else:
        profile.followers.add(request.user)
    return redirect('accounts:profile', profile_id)

@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')

09_MtoN/movie_pjt/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Genre, Movie, Score
from .forms import ScoreForm

# Create your views here.
def list(request):
    movies = Movie.objects.all()
    return render(request, 'movies/list.html', {'movies': movies})

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    score_form = ScoreForm()
    return render(request, 'movies/detail.html', {'movie': movie, 'score_form': score_form})

@login_required
@require_POST
def new_score(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    form = ScoreForm(request.POST)
    if form.is_valid():
        score = form.save(commit=False)
        score.user = request.user
        score.movie = movie
        score.save()
    return redirect('movies:detail', movie_pk)

@login_required
def delete_score(request, movie_pk, score_pk):
    score = get_object_or_404(Score, pk=score_pk)
    if score.user == request.user:
        score.delete()
    return redirect('movies:detail', movie_pk)

09_MtoN/movie_pjt/accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="!">
</form>
{% endblock %}

09_MtoN/movie_pjt/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}

<h2>{{ profile.username }}</h2>

{% if not user.is_anonymous and user != profile %}
<div>
  {% if user in profile.followers.all %}
  <a class="btn btn-outline-primary" href="{% url 'accounts:follow' profile.id %}">Following</a>
  {% else %}
  <a class="btn btn-primary" href="{% url 'accounts:follow' profile.id %}">Follow</a>
  {% endif %}
</div>
{% endif %}

{% if user != profile %}
<div>
  <strong>followers</strong>
  <ul>
    {% for person in profile.followers.all %}
    <li>{{ person.username }}</li>
    {% endfor %}
  </ul>
</div>
{% else %}
<div>
  <strong>followings 추천 영화</strong>
  <ul>
    {% for recommend in recommends %}
    <li>{{ recommend.0 }} - {{ recommend.1 }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}

{% endblock %}

09_MtoN/movie_pjt/accounts/templates/accounts/user_list.html
{% extends 'base.html' %}
{% block body %}
<div>
  <h2>Users</h2>
  <ul>
    {% for user in users %}
    <li><a href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

09_MtoN/movie_pjt/movie_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">영화추천</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movies:list' %}">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_list' %}">Users</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

09_MtoN/movie_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h2>{{ movie.title }}</h2>

<img src="{{ movie.poster_url }}" style="width:10rem;" alt="{{ movie.title }}">
<p>장르: {{ movie.genre.name }}</p>
<p>관객 수: {{ movie.audience }}</p>
<p>{{ movie.description }}</p>

{% if user.is_authenticated %}
<div class="card-body col-4 col-lg-2 col-md-3 col-sm-4">
  <form method="POST" action="{% url 'movies:new_score' movie.id %}">
    {% csrf_token %}
    {% bootstrap_form score_form %}
    <button type="submit" class="btn btn-info">평점 남기기</button>
  </form>
</div>
{% endif %}

<div class="card-body">
  <h5>평점</h5>
  {% for score in movie.score_set.all %}
  <div class="card-text">
    <strong>{{ score.user.username }}</strong> {{ score.score }}
    {% if score.user == request.user %}
      <a href="{% url 'movies:delete_score' movie.id score.id %}">[X]</a>
    {% endif %}
  </div>
  {% empty %}
  <div>평점이 없습니다.</div>
  {% endfor %}
</div>

{% endblock %}

09_MtoN/movie_pjt/movies/templates/movies/list.html
{% extends 'base.html' %}
{% block body %}
<h1>Movies List</h1>

<div class="row">
  {% for movie in movies %}
  <div class="card" style="width:10rem;">
    <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}" class="card-img-top" alt="{{ movie.title }}"></a>
    <div class="card-body">
      <h5 class="card-title">{{ movie.title }}</h5>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}