07_database/project07/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('new/', views.movie_create, name='movie_create'),
    path('<int:movie_id>/', views.movie_read, name='movie_read'),
    path('<int:movie_id>/edit', views.movie_update, name='movie_update'),
    path('<int:movie_id>/delete', views.movie_delete, name='movie_delete'),
    path('<int:movie_id>/scores/new', views.score_create, name='score_create'),
    path('<int:movie_id>/scores/<int:score_id>/delete', views.score_delete, name='score_delete'),
]

07_database/project07/project07/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

07_database/project07/movies/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=20, default='')

    def __str__(self):
        return f'{self.name[:10]}'


class Movie(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, default='')
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140, default='')
    description = models.TextField()

    def __str__(self):
        return f'{self.genre.name[:10]}: {self.title[:20]}'


class Score(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=140, default='')
    score = models.IntegerField()

    def __str__(self):
        return f'{self.movie.title[:20]}: {self.score}'

07_database/project07/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Genre, Movie, Score


# Create your views here.
def movie_list(request):
    movies = Movie.objects.all().order_by('-id')
    context = {
        'movies': movies,
    }
    return render(request, 'movies/list.html', context)


def movie_create(request):
    if request.method == 'POST':
        genre = get_object_or_404(Genre, id=request.POST.get('genre_id'))
        movie = Movie()
        movie.genre = genre
        movie.audience = request.POST.get('audience')
        movie.description = request.POST.get('description')
        movie.poster_url = request.POST.get('poster_url')
        movie.title = request.POST.get('title')
        movie.save()
        return redirect('movies:movie_read', movie.id)
    elif request.method == 'GET':
        return render(request, 'movies/new.html')


def movie_read(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    scores = movie.score_set.all()
    context = {
        'movie': movie,
        'scores': scores,
    }
    return render(request, 'movies/detail.html', context)


def movie_update(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'GET':
        context = {
            'movie': movie
        }
        return render(request, 'movies/edit.html', context)
    elif request.method == 'POST':
        genre = get_object_or_404(Genre, id=request.POST.get('genre_id'))
        movie.genre = genre
        movie.audience = request.POST.get('audience')
        movie.description = request.POST.get('description')
        movie.poster_url = request.POST.get('poster_url')
        movie.title = request.POST.get('title')
        movie.save()
        return redirect('movies:movie_read', movie.id)


def movie_delete(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:movie_list')
    elif request.method == 'GET':
        return redirect('movies:movie_read', movie.id)


def score_create(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        score = Score()
        score.movie = movie
        score.score = request.POST.get('score')
        score.content = request.POST.get('content')
        score.save()
    return redirect('movies:movie_read', movie.id)


def score_delete(request, movie_id, score_id):
    movie = get_object_or_404(Movie, id=movie_id)
    score = get_object_or_404(Score, id=score_id)
    if request.method == 'POST':
        score.delete()
    return redirect('movies:movie_read', movie.id)

07_database/project07/movies/templates/movies/_score.html
<div class="col-12 col-md-6">
    <div class="card mb-2">
        <div class="card-body">
            <form action="{% url 'movies:score_create' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="score">score: </label>
                <input type="number" id="score" name="score">
                <label for="content">content:</label>
                <input type="text" id="content" name="content">
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
    <div class="card">
        <ul class="list-group list-group-flush">
            {% if scores %}
                {% for score in scores %}
                    <li>{{ score.score }} - {{ score.content }}</li>
                    <form action="{% url 'movies:score_delete' movie.id score.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">[x]</button>
                    </form>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</div>

07_database/project07/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>Movies {% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block body %}
    {% endblock %}
    <hr>
    {% block button %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

07_database/project07/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block title %}- {{ movie.title }}{% endblock %}

{% block body %}
    <div class="row mt-3">
    <div class="col-12 col-md-6">
        <div class="card mb-2">
            <img src="{{ movie.poster_url }}" alt="{{ movie.title }}" width="960" class="card-img-top">
            <div class="card-body">
                <p class="card-text">
                    {{ movie.title }}
                    <hr>
                    {{ movie.genre }}
                    <hr>
                    관람객 {{ movie.audience }}명
                    <hr>
                    {{ movie.description }}
                </p>
            </div>
        </div>
    </div>
    {% include 'movies/_score.html' %}
</div>
{% endblock %}

{% block button %}
    <a href="{% url 'movies:movie_list' %}">
        <button>Movie list</button>
    </a>
    <a href="{% url 'movies:movie_update' movie.id %}">
        <button type="submit">Edit</button>
    </a>
    <form action="{% url 'movies:movie_delete' movie.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('삭제?')">Delete</button>
    </form>
{% endblock %}

07_database/project07/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}

{% block title %}- Edit {{ movie.title }}{% endblock %}

{% block body %}
    <h1>Edit {{ movie.title }}</h1>
    <form action="{% url 'movies:movie_update' movie.id %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="genre_id">Genre: </label>
            <select name="genre_id" id="genre_id" value="{{ movie.genre_id }}">
                <option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>
                <option>6</option><option>7</option><option>8</option><option>9</option><option>10</option><option>11</option>
            </select>
        </div>
        <div>
            <label for="title">Title: </label>
            <input type="text" name="title" id="title" value="{{ movie.title }}">
        </div>
        <div>
            <label for="audience">Audience: </label>
            <input type="text" name="audience" id="audience" value="{{ movie.audience }}">
        </div>
        <div>
            <label for="poster_url">Poster URL: </label>
            <input type="text" name="poster_url" id="poster_url" value="{{ movie.poster_url }}">
        </div>
        <div>
            <label for="description">Description: </label>
            <textarea name="description" id="description" cols="30" rows="10">{{ movie.description }}</textarea>
        </div>
        <div>
            <button type="submit">Submit</button>
        </div>
    </form>
{% endblock %}

{% block button %}
    <a href="{% url 'movies:movie_read' movie.id %}">
        <button>Go back</button>
    </a>
{% endblock %}

07_database/project07/movies/templates/movies/list.html
{% extends 'movies/base.html' %}

{% block title %}- list{% endblock %}

{% block body %}
    <h1>Movie list</h1>
    {% if movies %}
        <ul>
            {% for movie in movies %}
                <li>
                    <a href="{% url 'movies:movie_read' movie.id %}">
                       {{ movie.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

{% block button %}
    <a href="{% url 'movies:movie_create' %}">
        <button>New movie</button>
    </a>
{% endblock %}

07_database/project07/movies/templates/movies/new.html
{% extends 'movies/base.html' %}

{% block title %}- New{% endblock %}

{% block body %}
    <h1>New Article</h1>
    <form action="{% url 'movies:movie_create' %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="genre_id">Genre: </label>
            <select name="genre_id" id="genre_id">
                <option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>
                <option>6</option><option>7</option><option>8</option><option>9</option><option>10</option><option>11</option>
            </select>
        </div>
        <div>
            <label for="title">Title: </label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="audience">Audience: </label>
            <input type="text" name="audience" id="audience">
        </div>
        <div>
            <label for="poster_url">Poster URL: </label>
            <input type="text" name="poster_url" id="poster_url">
        </div>
        <div>
            <label for="description">Description: </label>
            <textarea name="description" id="description" cols="30" rows="10"></textarea>
        </div>
        <div>
            <button type="submit">Submit</button>
        </div>
    </form>
{% endblock %}

{% block button %}
    <a href="{% url 'movies:movie_list' %}">
        <button>Movie list</button>
    </a>
{% endblock %}